In [5]:
import numpy as np

In [4]:
a=np.zeros(3,dtype=int)

AttributeError: module 'numpy' has no attribute 'zeros'

In [3]:
a

array([0, 0, 0])

In [4]:
b=np.asarray([[1,2],[3,4]],dtype=int)

In [5]:
b

array([[1, 2],
       [3, 4]])

In [7]:
np.sum(b,axis=0)

array([4, 6])

In [5]:
np.sum(b,axis=1)

array([3, 7])

In [9]:
import numpy as np

s =  b'Hello World'
a = np.frombuffer(s, dtype =  'S1')
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [10]:
list=range(5)
it=iter(list)

In [11]:
x=np.fromiter(it,dtype=int)

In [12]:
print(x)

[0 1 2 3 4]


In [15]:
a = np.linspace(10, 12,  5, endpoint =  True)
print(a)

[10.  10.5 11.  11.5 12. ]


In [16]:
b=np.random.random(5)
print(b)

[0.56511786 0.87785117 0.86526071 0.82153652 0.09343963]


In [17]:
b[1:]

array([0.87785117, 0.86526071, 0.82153652, 0.09343963])

In [18]:
b[1]

0.877851166032028

In [8]:
c=np.random.random((2,3,4))

In [9]:
c

array([[[0.68665348, 0.17367752, 0.22147858, 0.59066245],
        [0.91288808, 0.56765496, 0.42739953, 0.60371833],
        [0.85471018, 0.40393944, 0.84050543, 0.59018804]],

       [[0.53567886, 0.85905892, 0.54858854, 0.25267769],
        [0.08828235, 0.17455079, 0.55061325, 0.06436036],
        [0.21545674, 0.03068614, 0.79518656, 0.98423112]]])

In [10]:
c.shape

(2, 3, 4)

In [22]:
c[0][0][0]

0.013180651124154119

In [24]:
c.sum(axis=2)

array([[1.94263241, 3.05000282, 2.06421768],
       [2.73771621, 2.35443603, 2.68408288]])